name: Update Changelog

on:
  release:
    types: [created]

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from your repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Install the github_changelog_generator gem locally
      - name: Install github_changelog_generator locally
        run: |
          gem install --user-install github_changelog_generator
          export PATH="$HOME/.gem/ruby/3.0.0/bin:$PATH"

      # Step 3: Generate CHANGELOG.md
      - name: Generate CHANGELOG.md
        run: |
          export PATH="$HOME/.gem/ruby/3.0.0/bin:$PATH"
          github_changelog_generator \
            --user ${{ github.repository_owner }} \
            --project ${{ github.event.repository.name }} \
            --token ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Commit and push the updated CHANGELOG.md using the GitHub Actions bot
      - name: Commit and push CHANGELOG.md
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md for release ${{ github.event.release.tag_name }}"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
